# Generated by Django 5.0.3 on 2024-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Menu/photos/'),
        ),
    ]
