# Generated by Django 5.0.3 on 2024-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_no',
            field=models.TextField(unique=True),
        ),
    ]
